/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2020 Toha <tohenk@yahoo.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package id.my.kasirq;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.lang.reflect.Field;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

import id.my.kasirq.model.Store;
import id.my.kasirq.util.IconLoader;

public class AppMain extends JFrame implements ActionListener {

    private Image image;

    public AppMain() {
        initComponents();
        initialize();
        bindHandlers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setMnemonic('F');
        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setMnemonic('K');
        jMenuItem1.setText("Pengaturan");
        jMenuItem1.setActionCommand("SETTINGS");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem6.setMnemonic('T');
        jMenuItem6.setText("Toko");
        jMenuItem6.setActionCommand("STORE");
        jMenu1.add(jMenuItem6);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem3.setMnemonic('P');
        jMenuItem3.setText("Produk");
        jMenuItem3.setActionCommand("PRODUCT");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem4.setMnemonic('I');
        jMenuItem4.setText("Invoice");
        jMenuItem4.setActionCommand("INVOICE");
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator2);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setMnemonic('e');
        jMenuItem2.setText("Keluar");
        jMenuItem2.setActionCommand("EXIT");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('A');
        jMenu2.setText("About");

        jMenuItem5.setText("About");
        jMenuItem5.setActionCommand("ABOUT");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initialize() {
        Dimension sz = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(0, 0);
        setSize(sz.width, sz.height);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        IconLoader iconLoader = IconLoader.getInstance();
        iconLoader.register(this, "EXIT", "sign-out-alt");
        iconLoader.register(this, "ABOUT", "info");
        iconLoader.register(this, "SETTINGS", "cog");
        iconLoader.register(this, "STORE", "store");
        iconLoader.register(this, "PRODUCT", "shopping-cart");
        iconLoader.register(this, "INVOICE", "cash-register");
        iconLoader.setAppIcon(this);
    }

    private void bindHandlers() {
        IconLoader iconLoader = IconLoader.getInstance();
        for (Field f: AppMain.class.getDeclaredFields()) {
            try {
                Object o = f.get(this);
                if (o instanceof JMenuItem) {
                    JMenuItem menuitem = (JMenuItem) o;
                    menuitem.addActionListener(this);
                    iconLoader.setIcon(this, menuitem);
                }
            }
            catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    private int getSetupLevel(int level) {
        AppData d = AppData.getInstance();
        if (level >= 1) {
            Store store = d.getActiveStore();
            if (store == null || store.getNama() == null) {
                JOptionPane.showMessageDialog(this,
                        "Toko perlu dikonfigurasi terlebih dahulu!",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
                return 1;
            }
        }
        if (level >= 2) {
            if (d.getProduct().getObjects().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Belum ada produk dibuat!",
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
                return 2;
            }
        }
        return 0;
    }
    
    private boolean isNeedSetup(int level) {
        boolean res = false;
        switch (getSetupLevel(level)) {
            case 1:
                res = true;
                StoreDialog.getInstance().setVisible(true);
                break;
            case 2:
                res = true;
                ProductDialog.getInstance().setVisible(true);
                break;
        }
        return res;
    }

    public void setImage(Image img) {
        image = img;
    }
    
    public void updateTitle() {
        Store store = AppData.getInstance().getActiveStore();
        String title = store != null && store.getNama() != null ?
                String.format("%s \u2013 %s", store.getNama(), App.NAME) : App.NAME;
        setTitle(title);
    }

    protected void setAntialiasing(Graphics2D g2, boolean value) {
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, value ?
                RenderingHints.VALUE_ANTIALIAS_ON :
                RenderingHints.VALUE_ANTIALIAS_OFF);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;
        setAntialiasing(g2, true);
        if (image != null) {
            Dimension sz = getSize();
            int x = (sz.width - image.getWidth(null)) / 2;
            int y = (sz.height - image.getHeight(null)) / 2;
            g2.drawImage(image, x, y, null);
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals("EXIT")) {
            if (JOptionPane.showConfirmDialog(this, "Anda yakin untuk keluar?",
                    "Konfirmasi", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                System.exit(0);
            }
        }
        if (e.getActionCommand().equals("ABOUT")) {
            JOptionPane.showMessageDialog(this, App.NAME + " \u00a9 2020 " +
                    "Toha \u2013 1461900005\n" +
                    "Teknik Informatika\n" +
                    "Universitas 17 Agustus 1945 Surabaya",
                    "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        if (e.getActionCommand().equals("SETTINGS")) {
            SetupDialog.getInstance().setVisible(true);
        }
        if (e.getActionCommand().equals("STORE")) {
            StoreDialog.getInstance().setVisible(true);
        }
        if (e.getActionCommand().equals("PRODUCT")) {
            if (!isNeedSetup(1)) {
                ProductDialog.getInstance().setVisible(true);
            }
        }
        if (e.getActionCommand().equals("INVOICE")) {
            if (!isNeedSetup(2)) {
                InvoiceDialog.getInstance().setVisible(true);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
